# Generated by Django 4.0 on 2022-01-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mido', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
