# Generated by Django 4.0 on 2022-01-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mido', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='midomodel',
            name='manage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
